deploy:
  runs-on: windows-latest
  needs: build
  environment:
    name: 'production'
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  permissions:
    id-token: write
  env:
    DB_URL: ${{ secrets.DB_URL }}
    DB_USERNAME: ${{ secrets.DB_USERNAME }}
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: java-app
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.__clientidsecretname__ }}
        tenant-id: ${{ secrets.__tenantidsecretname__ }}
        subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'stock-market-sim'
        slot-name: 'production'
        package: '*.war'
